[package]
name = "cf_rh320u_93_reader"
description = "Library for using CHAFON CF-RH320U-93 (ISO 15693) USB card reader"
authors = ["Michael Wright <maiklpolkovnikov@gmail.com>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
rusb = "0.9.1"